<a href="https://colab.research.google.com/github/maggiecrowner/DS5001-Final-Project/blob/main/DerivedTables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Derived Tables

In [1]:
! git clone https://github.com/maggiecrowner/DS5001-Final-Project.git

Cloning into 'DS5001-Final-Project'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 109 (delta 21), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (109/109), 9.81 MiB | 4.22 MiB/s, done.
Resolving deltas: 100% (21/21), done.

In [2]:
!wget -O CORPUS.csv "https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv"
!wget -O LIB.csv "https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv"
!wget -O VOCAB.csv "https://virginia.box.com/shared/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv"

--2026-04-12 20:16:43--  https://virginia.box.com/shared/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-12 20:16:43--  https://virginia.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv [following]
--2026-04-12 20:16:43--  https://virginia.app.box.com/public/static/ijkqovrdgvrmctsdqobymig2p98q9x0m.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!a0W9bMHqaX_QGJGhapQtsmf_Hp5aQXaaU0phqtWlJgzKp2rYlG1b5zv2gL5B3t0934o25oOjC5qX3IimI744g96Et7dCMsHQnj4adVyNgpEOK363L9apLB0wjKQ5GdPniHl4zKaJ23d7Ntj453ds7UCQoAZ6TaFiFhM3x6-9_9ibSqlT8GseBulzy6Ft-RT9lHZDFLeHKY2k96sQuDydIa5teGBe7EJ8ibgo1SW1-9W1H1wSGjUAgbqBFhesWiamkHKeCz1PHZcd_bI7aco6wZokSiFt-7nDJhuGfYhCrNwdTDDWZUmm5UuS9IrcDdZgBdcoJRW1pAJWwiWlFCaZ-rNUNqHpbhiTmq0N8yjnt0T3oJi_E9M3K3uNNwgoGeEK6w-6hU6UeoQTtFvaScHOf-7DCLjJR_bQEdWOEfpO-kCRWzNAntJycyWxXLtyELbIqmTpQbsPOl62svD-dpodlcKYVkaWvs3jdXhr856moY35zoDHtOj9h77RllNtuRCj73oVJCy7kezcwg6Nv0K8RSHKRY7NBjJu8WNXHMeFKBjTFTzaESUOJNiCzRGtbpl7vFGN5QI79wDSxT6xPWnMGbi2uy7mBrFRQw5FGWACGntXVxu-0Qt1WorEPAp_0IkfQHanp3H0SknfP_Z_nPaXNTQUfQQWL8KcbjtMEjoGho8PA0UlUNayATQqnnykyjAmknGgcMKnl2H5ue-5CXF0oTHG1SX84om3Hup0Bi7lpOabj-XHvhQVZ3mc9-bfjeESpTXnvQs0OS5ox_trD-G8aIVSLUkwqEK_0NDlplMv-owvT6u-zkdDO_uRLSGdxnlu07mvKuDwgLkLDsFnFbZF1vL5ZTAfmHolJzCex2AsbJ65ABzkNIETJv-ZXdm6aHBVcZoBi87D7Bw0svOzGKYqbtcVO8bDopdCM1P3DNxXPySJMPzeHGd15rDDDHvMN4yhP8piOlabsJmmXydYAewa_aaj42sopbg1JjkUYltkqkw3cCY5XX2AAPbt3llYiu5306fC-Uj6a2LcohhCLMB36loFFAaLwqarWrEVyKqdWSpmPNpCSPk4HHDBUPYmNgPsh3kTSHq4-E47wb3Z_xYcqL056M3JFqVB8xFMrtnnyXg3bhLCfzq3FdDHBNse1gp92TSqZBYaPIgddzrM_E3qoXQhZ62-z5_gb20RnKYYmDARWficms8KtmMzXbmcZaDnn-giN2044M93_kb9CoviYzux0JlIPfow59P4eFmmbODpYmL8iBtIxuNBXvUzjtVUFmqAVc6neQUp1irFR_FVoq9Iigk8aGy2jCd3rm_74gzhMxw-l0Sjypu9TZ1PUvleSxDU6V41HbBAOw7BD2CeTBnC9ltPqn0t05BsZbMnRyvgzdwX8P2gbw-j3lxlgEZcfhfk6zEYcUvoIG34zQariSvdaJ0rqPjfHMhLnF8vUyoLPY4EWcLDbHB652oiXIKt6ItNazX-Da9GlJBo8qbOfWpMfhgLOeSh/download [following]
--2026-04-12 20:16:43--  https://public.boxcloud.com/d/1/b1!a0W9bMHqaX_QGJGhapQtsmf_Hp5aQXaaU0phqtWlJgzKp2rYlG1b5zv2gL5B3t0934o25oOjC5qX3IimI744g96Et7dCMsHQnj4adVyNgpEOK363L9apLB0wjKQ5GdPniHl4zKaJ23d7Ntj453ds7UCQoAZ6TaFiFhM3x6-9_9ibSqlT8GseBulzy6Ft-RT9lHZDFLeHKY2k96sQuDydIa5teGBe7EJ8ibgo1SW1-9W1H1wSGjUAgbqBFhesWiamkHKeCz1PHZcd_bI7aco6wZokSiFt-7nDJhuGfYhCrNwdTDDWZUmm5UuS9IrcDdZgBdcoJRW1pAJWwiWlFCaZ-rNUNqHpbhiTmq0N8yjnt0T3oJi_E9M3K3uNNwgoGeEK6w-6hU6UeoQTtFvaScHOf-7DCLjJR_bQEdWOEfpO-kCRWzNAntJycyWxXLtyELbIqmTpQbsPOl62svD-dpodlcKYVkaWvs3jdXhr856moY35zoDHtOj9h77RllNtuRCj73oVJCy7kezcwg6Nv0K8RSHKRY7NBjJu8WNXHMeFKBjTFTzaESUOJNiCzRGtbpl7vFGN5QI79wDSxT6xPWnMGbi2uy7mBrFRQw5FGWACGntXVxu-0Qt1WorEPAp_0IkfQHanp3H0SknfP_Z_nPaXNTQUfQQWL8KcbjtMEjoGho8PA0UlUNayATQqnnykyjAmknGgcMKnl2H5ue-5CXF0oTHG1SX84om3Hup0Bi7lpOabj-XHvhQVZ3mc9-bfjeESpTXnvQs0OS5ox_trD-G8aIVSLUkwqEK_0NDlplMv-owvT6u-zkdDO_uRLSGdxnlu07mvKuDwgLkLDsFnFbZF1vL5ZTAfmHolJzCex2AsbJ65ABzkNIETJv-ZXdm6aHBVcZoBi87D7Bw0svOzGKYqbtcVO8bDopdCM1P3DNxXPySJMPzeHGd15rDDDHvMN4yhP8piOlabsJmmXydYAewa_aaj42sopbg1JjkUYltkqkw3cCY5XX2AAPbt3llYiu5306fC-Uj6a2LcohhCLMB36loFFAaLwqarWrEVyKqdWSpmPNpCSPk4HHDBUPYmNgPsh3kTSHq4-E47wb3Z_xYcqL056M3JFqVB8xFMrtnnyXg3bhLCfzq3FdDHBNse1gp92TSqZBYaPIgddzrM_E3qoXQhZ62-z5_gb20RnKYYmDARWficms8KtmMzXbmcZaDnn-giN2044M93_kb9CoviYzux0JlIPfow59P4eFmmbODpYmL8iBtIxuNBXvUzjtVUFmqAVc6neQUp1irFR_FVoq9Iigk8aGy2jCd3rm_74gzhMxw-l0Sjypu9TZ1PUvleSxDU6V41HbBAOw7BD2CeTBnC9ltPqn0t05BsZbMnRyvgzdwX8P2gbw-j3lxlgEZcfhfk6zEYcUvoIG34zQariSvdaJ0rqPjfHMhLnF8vUyoLPY4EWcLDbHB652oiXIKt6ItNazX-Da9GlJBo8qbOfWpMfhgLOeSh/download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.165, 2620:117:bff0:69::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70080896 (67M) [text/csv]
Saving to: ‘CORPUS.csv’

CORPUS.csv          100%[===================>]  66.83M   106MB/s    in 0.6s

2026-04-12 20:16:44 (106 MB/s) - ‘CORPUS.csv’ saved [70080896/70080896]

--2026-04-12 20:16:44--  https://virginia.box.com/shared/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-12 20:16:44--  https://virginia.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv [following]
--2026-04-12 20:16:44--  https://virginia.app.box.com/public/static/fhzudg34je9xls5bfcbi4xdnaiek74rj.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!8h7jNaUYhhHoeEYbxfgOYD__HySxEZKGM1Nh_gtg2LVTjBhCcpsYlxdT-gX9PZ8QG8EcqarbKsX5SDlRwAloGaw4jm3KyUttpQXj9CgU_S8ynsRB2tZ1i4JK_wyDdtSq9MwOl7klkLkLzmU_pbVKiAtXzLFi3WdCJ9B31r-naKAfhq3ot9vrfX1KE2G8vdndllxU2PBHdm0IRhwYFqKrkhXmMo4YfYdkYmreWqZ3eSZKN9GncUuOvW_Eu4tyRp4ALjmalf2kMnnuzaN3GFif7W6_hKTr1D4Wdk9JO2gTuIdnv9PDmRsCeoVYGqaNXc1TNjaayCU1Q3t6vGP9lrXZ__ZQd_A0oKDGAtrXrFeS5CrzVBEig6eqiQRKuUlnuebd3e-kGdGwgwIOF_FwgYM1znX6Tzv0cUjg9o3a9GqjDPD_RGG0gwjuamv5UkT0ZPTyizT8jI3z7gMM6wyX_own7U4SQOu7F-uPFztw3Ehshk59KiYtuuvE1TgK3kfXxEt2nMWvk5eU0-sglqf-kPgdU-zDjD-xUZiDMwI6s08MFKzuWkkfK6La3cKxaagwFy95Lm0PL0Pnmj8ETQvztF7gBNbULRIvHEGv7ggqWBHGCoB3KtNZHJW3sokIRGO7n3PWC7UQCSSk7LogURaA5YV727GwHxKliXvOKdLjltMWB1CSLwHIdWiq-4Ed5FkMn00uzNnOud2KQ0GEd-aH17Y5_cuN1rccERv-sK1sfVuRElsd-SnGGkIF8z72RM6yj8nrM1K9uEvZEztkozQeJ0SHlzd5YOQFiJXxjYI0bEVIVCvW7UD3SGs_XDES6BNG8ab8ROqZwBBr46oPvlw3Zv8ww3Fdd00T1dMIEuDnHAeRySGJC_qybwx05KV6IW-BCwZ12jM_Mv9jyE0Ucg7vDKQSuz7Cwos9ItPBhKtu5HSpQ3WtXU1iLHdTO15sRLEBLKtNP8Er1Rjpx55Wwqjsd15KIRPJMYIi7MX8RIBbBCSZXdryR-hR6Vumnei8x1PW1J9IgIkrYfimRngvJlqco9kVP7NPnxMcF2lBBddlxUnw2F9CVIuphgLn_r8aL5g0OPHl-Fk2OLN9vY-4iMNctmw2BByL_Lf-O2eEUdXrTut75zEl5pDMXDyFT8yUnmPgz3SWefCXrlJh6Jy6iL_wp2vCOCo-6hEZxoe8YkmGQTvfJk11woZ56EDyqgt8FfpzZFYHEto4bhoJwPoy8att6CkkS91yG8JAM5m98uuPw1CZ28oWCQildWTZDhqsdwqenj-55Pgk0OSB83XB4djbCHkjAJ6MSDrEguRfQnmjBOsL0WFj9b3WPtOdV4b8Q4n4bWMMrJBmr_9HJkQL5ZdEYi_lZGH1IUOV7U2KvXi28j3qpqGSD5XZny5aK-IrNbnT_wa0xTAYe09hNtrsOk4eki6nA2tBCibqHTZSIKR_j8hOo2PIThA7A9Wpn4NuK_QVOJwULST_4Qul7EOG6inYcUtgbZy5SA../download [following]
--2026-04-12 20:16:45--  https://public.boxcloud.com/d/1/b1!8h7jNaUYhhHoeEYbxfgOYD__HySxEZKGM1Nh_gtg2LVTjBhCcpsYlxdT-gX9PZ8QG8EcqarbKsX5SDlRwAloGaw4jm3KyUttpQXj9CgU_S8ynsRB2tZ1i4JK_wyDdtSq9MwOl7klkLkLzmU_pbVKiAtXzLFi3WdCJ9B31r-naKAfhq3ot9vrfX1KE2G8vdndllxU2PBHdm0IRhwYFqKrkhXmMo4YfYdkYmreWqZ3eSZKN9GncUuOvW_Eu4tyRp4ALjmalf2kMnnuzaN3GFif7W6_hKTr1D4Wdk9JO2gTuIdnv9PDmRsCeoVYGqaNXc1TNjaayCU1Q3t6vGP9lrXZ__ZQd_A0oKDGAtrXrFeS5CrzVBEig6eqiQRKuUlnuebd3e-kGdGwgwIOF_FwgYM1znX6Tzv0cUjg9o3a9GqjDPD_RGG0gwjuamv5UkT0ZPTyizT8jI3z7gMM6wyX_own7U4SQOu7F-uPFztw3Ehshk59KiYtuuvE1TgK3kfXxEt2nMWvk5eU0-sglqf-kPgdU-zDjD-xUZiDMwI6s08MFKzuWkkfK6La3cKxaagwFy95Lm0PL0Pnmj8ETQvztF7gBNbULRIvHEGv7ggqWBHGCoB3KtNZHJW3sokIRGO7n3PWC7UQCSSk7LogURaA5YV727GwHxKliXvOKdLjltMWB1CSLwHIdWiq-4Ed5FkMn00uzNnOud2KQ0GEd-aH17Y5_cuN1rccERv-sK1sfVuRElsd-SnGGkIF8z72RM6yj8nrM1K9uEvZEztkozQeJ0SHlzd5YOQFiJXxjYI0bEVIVCvW7UD3SGs_XDES6BNG8ab8ROqZwBBr46oPvlw3Zv8ww3Fdd00T1dMIEuDnHAeRySGJC_qybwx05KV6IW-BCwZ12jM_Mv9jyE0Ucg7vDKQSuz7Cwos9ItPBhKtu5HSpQ3WtXU1iLHdTO15sRLEBLKtNP8Er1Rjpx55Wwqjsd15KIRPJMYIi7MX8RIBbBCSZXdryR-hR6Vumnei8x1PW1J9IgIkrYfimRngvJlqco9kVP7NPnxMcF2lBBddlxUnw2F9CVIuphgLn_r8aL5g0OPHl-Fk2OLN9vY-4iMNctmw2BByL_Lf-O2eEUdXrTut75zEl5pDMXDyFT8yUnmPgz3SWefCXrlJh6Jy6iL_wp2vCOCo-6hEZxoe8YkmGQTvfJk11woZ56EDyqgt8FfpzZFYHEto4bhoJwPoy8att6CkkS91yG8JAM5m98uuPw1CZ28oWCQildWTZDhqsdwqenj-55Pgk0OSB83XB4djbCHkjAJ6MSDrEguRfQnmjBOsL0WFj9b3WPtOdV4b8Q4n4bWMMrJBmr_9HJkQL5ZdEYi_lZGH1IUOV7U2KvXi28j3qpqGSD5XZny5aK-IrNbnT_wa0xTAYe09hNtrsOk4eki6nA2tBCibqHTZSIKR_j8hOo2PIThA7A9Wpn4NuK_QVOJwULST_4Qul7EOG6inYcUtgbZy5SA../download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.165, 2620:117:bff0:69::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 333596 (326K) [text/csv]
Saving to: ‘LIB.csv’

LIB.csv             100%[===================>] 325.78K  --.-KB/s    in 0.06s

2026-04-12 20:16:45 (5.19 MB/s) - ‘LIB.csv’ saved [333596/333596]

--2026-04-12 20:16:45--  https://virginia.box.com/shared/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv
Resolving virginia.box.com (virginia.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.box.com (virginia.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv [following]
--2026-04-12 20:16:45--  https://virginia.box.com/public/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv
Reusing existing connection to virginia.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://virginia.app.box.com/public/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv [following]
--2026-04-12 20:16:45--  https://virginia.app.box.com/public/static/a2njs9ipjxrgam9un7sr4yn3f6f196ny.csv
Resolving virginia.app.box.com (virginia.app.box.com)... 74.112.186.157, 2620:117:bff0:12d::
Connecting to virginia.app.box.com (virginia.app.box.com)|74.112.186.157|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!R1mZTjhLlB5-nwpfks8So30K-BS5LQg1DKOufkUJZ_tYjaVIUCsZDoWenc6KjxuZ1-Jj1rjEaH4qZ2WAXow-qI-Gsg0absGWUGZ7iajEgWtsSlX2e_FyPyjoTqOLs5l7tcB46HGIHt6KkEogyAD9N9hWwkfeoj2-h8w-4FLq9dg4K2ZwPDDM6q_n-pokp5s0ij3W3R0Ma2XTR9fRGhRvEjcLM-AVOAq6t7b_F_0kxQz1yS5fW_xGWPYT1CR_G1XTGPMSG3mOgZHzdk9n0aH8bud06bVhVJmXwGtuLcQDQDKaT-jHyaybqFt6yTqCpOOsumA77uRxd-a4_zeO9NCPZtFE217UjRRwtR99DKf43_zx5FJkOYOOmttKR9ulNQhMaWqeF8ZAEuBLibe2BtJnp8jTLcr4fgvM2f7UrG4nPTVP8QbemgxgIzgJXOHxxe2rcu2X70LwJhnrc0ISRRMJjNXvqxkF51cc_8et2nqMgfhbV06lWF5_8zTbkisO3XRj-Lkn4B_EJMIYETK6LGHBEfwK7xdft1VwsAmjLLFzj2JOHQyfBLo51sl6gE0qid0I4lFBnT3lgTlSb6ZhHbkghcm2xRGh0Ffo1ogfJiwYWhhrXose1Ladle2tk_nj7T85BJnYVsZ9Mz9DzO6Ln2E69A_OR4tV9oY8ZC6Xlbcu9gqOxLlp-3Sm61NekNzV_kVJgvxwA8hFptY3NXR7xC-ZNiMY39Z-2wHiUboEbjBRg6_PWCfZSRSykbXQwD_Scgk9qoikdf9XC20OuJSRD12Q4Fj6CYcVBpOf08MSPCIV4LJR9Dqt64zF1NnmD0Uy8Ld9lxzfD766ikhuBcA4-TIjdVeymeD9sbFnTWLvHurB0vv8cgBPGaB9vbz8_3U9e43uk3AqP2fFAiwLxXE8tKGrFScjdQCzekyyr5E3peA-r2brzNtu5UPi8Vgukvm_T9uxS-Wkjk3fqTOmUQVNULK5yBnzG7tWpv246WsPXRGDMaIxKlnyKP5HRM234Eu-Gdur0zzGBC8haraqo2vwPG67Bfms3nwjZMAWtZooKEG41U8LKkWJTf2gC8MyD7uI9NPa2GKKX5BGJm0wCBXa5NkebFGMrdZ-3yigzPt1fm_QcSshNtd8eApcnQPYNWlTYZl6cq9h0wIedotYr-Q7A4Y6-gJzlSbE9X8N-JFJBT1X156zQuEoRz233CBFLJkG93Ny606iRgAU_tn4z2zxNdNnOfM_z13BAB4gpg78C7BoyUPJGvgXvM47ql_t0Kz91zsjfjHod92ELhMWYdE2N7poQyrXKTSYW04FA191Q9HoVfv5Pkxq0zAp3MoJtBQwW7QRAAXWyw943ZovdKZd4jtb4AgirWQlVJGmbNxKBtoTWqyDj8BbIsC-WOjr0optd5I65OFJ0l0sa9VF4uFMmhfFkQ27t-djr19e6z9dDuLuIrlv7vgliPcLhJVK0wlegdy6IAE3Jz9Ch-oSLKcRi5YiaFchoGs0io0cS62iq1IQLcM66bWAmT6zw8ERDUQ7N8N4TeF028Gr736S9A../download [following]
--2026-04-12 20:16:45--  https://public.boxcloud.com/d/1/b1!R1mZTjhLlB5-nwpfks8So30K-BS5LQg1DKOufkUJZ_tYjaVIUCsZDoWenc6KjxuZ1-Jj1rjEaH4qZ2WAXow-qI-Gsg0absGWUGZ7iajEgWtsSlX2e_FyPyjoTqOLs5l7tcB46HGIHt6KkEogyAD9N9hWwkfeoj2-h8w-4FLq9dg4K2ZwPDDM6q_n-pokp5s0ij3W3R0Ma2XTR9fRGhRvEjcLM-AVOAq6t7b_F_0kxQz1yS5fW_xGWPYT1CR_G1XTGPMSG3mOgZHzdk9n0aH8bud06bVhVJmXwGtuLcQDQDKaT-jHyaybqFt6yTqCpOOsumA77uRxd-a4_zeO9NCPZtFE217UjRRwtR99DKf43_zx5FJkOYOOmttKR9ulNQhMaWqeF8ZAEuBLibe2BtJnp8jTLcr4fgvM2f7UrG4nPTVP8QbemgxgIzgJXOHxxe2rcu2X70LwJhnrc0ISRRMJjNXvqxkF51cc_8et2nqMgfhbV06lWF5_8zTbkisO3XRj-Lkn4B_EJMIYETK6LGHBEfwK7xdft1VwsAmjLLFzj2JOHQyfBLo51sl6gE0qid0I4lFBnT3lgTlSb6ZhHbkghcm2xRGh0Ffo1ogfJiwYWhhrXose1Ladle2tk_nj7T85BJnYVsZ9Mz9DzO6Ln2E69A_OR4tV9oY8ZC6Xlbcu9gqOxLlp-3Sm61NekNzV_kVJgvxwA8hFptY3NXR7xC-ZNiMY39Z-2wHiUboEbjBRg6_PWCfZSRSykbXQwD_Scgk9qoikdf9XC20OuJSRD12Q4Fj6CYcVBpOf08MSPCIV4LJR9Dqt64zF1NnmD0Uy8Ld9lxzfD766ikhuBcA4-TIjdVeymeD9sbFnTWLvHurB0vv8cgBPGaB9vbz8_3U9e43uk3AqP2fFAiwLxXE8tKGrFScjdQCzekyyr5E3peA-r2brzNtu5UPi8Vgukvm_T9uxS-Wkjk3fqTOmUQVNULK5yBnzG7tWpv246WsPXRGDMaIxKlnyKP5HRM234Eu-Gdur0zzGBC8haraqo2vwPG67Bfms3nwjZMAWtZooKEG41U8LKkWJTf2gC8MyD7uI9NPa2GKKX5BGJm0wCBXa5NkebFGMrdZ-3yigzPt1fm_QcSshNtd8eApcnQPYNWlTYZl6cq9h0wIedotYr-Q7A4Y6-gJzlSbE9X8N-JFJBT1X156zQuEoRz233CBFLJkG93Ny606iRgAU_tn4z2zxNdNnOfM_z13BAB4gpg78C7BoyUPJGvgXvM47ql_t0Kz91zsjfjHod92ELhMWYdE2N7poQyrXKTSYW04FA191Q9HoVfv5Pkxq0zAp3MoJtBQwW7QRAAXWyw943ZovdKZd4jtb4AgirWQlVJGmbNxKBtoTWqyDj8BbIsC-WOjr0optd5I65OFJ0l0sa9VF4uFMmhfFkQ27t-djr19e6z9dDuLuIrlv7vgliPcLhJVK0wlegdy6IAE3Jz9Ch-oSLKcRi5YiaFchoGs0io0cS62iq1IQLcM66bWAmT6zw8ERDUQ7N8N4TeF028Gr736S9A../download
Resolving public.boxcloud.com (public.boxcloud.com)... 74.112.186.165, 2620:117:bff0:69::
Connecting to public.boxcloud.com (public.boxcloud.com)|74.112.186.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1694430 (1.6M) [text/csv]
Saving to: ‘VOCAB.csv’

VOCAB.csv           100%[===================>]   1.62M  --.-KB/s    in 0.1s

2026-04-12 20:16:46 (12.0 MB/s) - ‘VOCAB.csv’ saved [1694430/1694430]

In [3]:
import pandas as pd
CORPUS = pd.read_csv('CORPUS.csv', delimiter='|')
LIB = pd.read_csv('LIB.csv', delimiter='|')
VOCAB = pd.read_csv('VOCAB.csv', delimiter='|')

## BOW

In [4]:
OHCO = ['Artist', 'Album', 'Title', 'token_str']
bags = dict(
    TITLES = OHCO[:3],
    ALBUMS = OHCO[:2],
    ARTISTS = OHCO[:1]
)

In [5]:
def create_bow(CORPUS, bag):
    bow = (
        CORPUS
        .groupby(bags[bag]+['term_str'])
        .term_str.count()
        .to_frame('n')
    )
    return bow

In [6]:
BOW = create_bow(CORPUS, bag='TITLES')
BOW.head()

                                                                             n
Artist        Album                                 Title         term_str
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You a         18
                                                                  all        6
                                                                  and        9
                                                                  around     2
                                                                  at         2

In [7]:
print('Number of observations:', len(BOW))

Number of observations: 236578

In [9]:
BOW.to_csv('/content/DS5001-Final-Project/BOW.csv', sep='|', index=True)

## DTM

In [10]:
DTM = BOW.n.unstack(fill_value=0)
DTM.head()

term_str                                                                        a  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              18
              Ariana Grande                         Ariana Grande Tour Guide    0
                                                    I’m Every Woman/Vogue      14
                                                    Leave Me Lonely (Reprise)   5
                                                    Love Me Harder/breathin     2

term_str                                                                       all  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                6
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        8
                                                    Leave Me Lonely (Reprise)    0
                                                    Love Me Harder/breathin      3

term_str                                                                       and  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                9
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        6
                                                    Leave Me Lonely (Reprise)    1
                                                    Love Me Harder/breathin     32

term_str                                                                       around  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   2
              Ariana Grande                         Ariana Grande Tour Guide        0
                                                    I’m Every Woman/Vogue           2
                                                    Leave Me Lonely (Reprise)       0
                                                    Love Me Harder/breathin         0

term_str                                                                       at  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You               2
              Ariana Grande                         Ariana Grande Tour Guide    0
                                                    I’m Every Woman/Vogue       0
                                                    Leave Me Lonely (Reprise)   0
                                                    Love Me Harder/breathin     0

term_str                                                                       away  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 1
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         1
                                                    Leave Me Lonely (Reprise)     1
                                                    Love Me Harder/breathin       1

term_str                                                                       be  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You               2
              Ariana Grande                         Ariana Grande Tour Guide    0
                                                    I’m Every Woman/Vogue       2
                                                    Leave Me Lonely (Reprise)   0
                                                    Love Me Harder/breathin     1

term_str                                                                       better  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   1
              Ariana Grande                         Ariana Grande Tour Guide        0
                                                    I’m Every Woman/Vogue           1
                                                    Leave Me Lonely (Reprise)       0
                                                    Love Me Harder/breathin         0

term_str                                                                       big  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                2
              Ariana Grande                         Ariana Grande Tour Guide     0
                                                    I’m Every Woman/Vogue        0
                                                    Leave Me Lonely (Reprise)    0
                                                    Love Me Harder/breathin      0

term_str                                                                       bitty  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  1
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0
                                                    Love Me Harder/breathin        0

term_str                                                                       ...  \
Artist        Album                                 Title                      ...
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              ...
              Ariana Grande                         Ariana Grande Tour Guide   ...
                                                    I’m Every Woman/Vogue      ...
                                                    Leave Me Lonely (Reprise)  ...
                                                    Love Me Harder/breathin    ...

term_str                                                                       wondrously  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                       0
              Ariana Grande                         Ariana Grande Tour Guide            0
                                                    I’m Every Woman/Vogue               0
                                                    Leave Me Lonely (Reprise)           0
                                                    Love Me Harder/breathin             0

term_str                                                                       morе  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0
              Ariana Grande                         Ariana Grande Tour Guide      0
                                                    I’m Every Woman/Vogue         0
                                                    Leave Me Lonely (Reprise)     0
                                                    Love Me Harder/breathin       0

term_str                                                                       pathway  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0
              Ariana Grande                         Ariana Grande Tour Guide         0
                                                    I’m Every Woman/Vogue            0
                                                    Leave Me Lonely (Reprise)        0
                                                    Love Me Harder/breathin          0

term_str                                                                       starlit  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0
              Ariana Grande                         Ariana Grande Tour Guide         0
                                                    I’m Every Woman/Vogue            0
                                                    Leave Me Lonely (Reprise)        0
                                                    Love Me Harder/breathin          0

term_str                                                                       travels  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0
              Ariana Grande                         Ariana Grande Tour Guide         0
                                                    I’m Every Woman/Vogue            0
                                                    Leave Me Lonely (Reprise)        0
                                                    Love Me Harder/breathin          0

term_str                                                                       bluegrass  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                      0
              Ariana Grande                         Ariana Grande Tour Guide           0
                                                    I’m Every Woman/Vogue              0
                                                    Leave Me Lonely (Reprise)          0
                                                    Love Me Harder/breathin            0

term_str                                                                       decoration  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                       0
              Ariana Grande                         Ariana Grande Tour Guide            0
                                                    I’m Every Woman/Vogue               0
                                                    Leave Me Lonely (Reprise)           0
                                                    Love Me Harder/breathin             0

term_str                                                                       jillian  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0
              Ariana Grande                         Ariana Grande Tour Guide         0
                                                    I’m Every Woman/Vogue            0
                                                    Leave Me Lonely (Reprise)        0
                                                    Love Me Harder/breathin          0

term_str                                                                       newer  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0
              Ariana Grande                         Ariana Grande Tour Guide       0
                                                    I’m Every Woman/Vogue          0
                                                    Leave Me Lonely (Reprise)      0
                                                    Love Me Harder/breathin        0

term_str                                                                       driftwood
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                      0
              Ariana Grande                         Ariana Grande Tour Guide           0
                                                    I’m Every Woman/Vogue              0
                                                    Leave Me Lonely (Reprise)          0
                                                    Love Me Harder/breathin            0

[5 rows x 15086 columns]

In [11]:
DTM.to_csv('/content/DS5001-Final-Project/DTM.csv', sep='|', index=True)

## TFIDF

In [12]:
import numpy as np

def get_tfidf(DTM, tf_method='sum', idf_method='standard', item_type='term_str'):

    if tf_method == 'sum':
        TF = (DTM.T / DTM.T.sum()).T
    elif tf_method == 'smooth':
        TF = (DTM.T / DTM.T.sum()).T + 1
    elif tf_method == 'max':
        TF = (DTM.T / DTM.T.max()).T
    elif tf_method == 'log':
        TF = (np.log2(1 + DTM.T)).T
    elif tf_method == 'raw':
        TF = DTM
    elif tf_method == 'bool':
        TF = DTM.astype('bool').astype('int')
    else:
        raise ValueError(f"TF method {tf_method} not found.")

    DF = DTM.astype('bool').sum()
    N = len(DTM)

    if idf_method == 'standard':
        IDF = np.log2(N / DF)
    elif idf_method == 'max':
        IDF = np.log2(DF.max() / DF)
    elif idf_method == 'plus':
        IDF = np.log2(N / DF) + 1
    elif idf_method == 'smooth':
        IDF = np.log2((1 + N) / (1 + DF)) + 1
    else:
        raise ValueError(f"IDF method {idf_method} not found.")

    TFIDF = TF * IDF

    return TFIDF

In [13]:
TFIDF = get_tfidf(DTM)
TFIDF.head()

term_str                                                                              a  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.017721
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.008773
                                                    Leave Me Lonely (Reprise)  0.021799
                                                    Love Me Harder/breathin    0.001403

term_str                                                                            all  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.014379
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.012204
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.005123

term_str                                                                            and  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.006469
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.002745
                                                    Leave Me Lonely (Reprise)  0.003183
                                                    Love Me Harder/breathin    0.016391

term_str                                                                         around  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.015731
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.010014
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                             at  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.010475
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                           away  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.007745
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.004930
                                                    Leave Me Lonely (Reprise)  0.034299
                                                    Love Me Harder/breathin    0.005519

term_str                                                                             be  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.004312
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.002745
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.001536

term_str                                                                         better  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.009343
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.005948
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                            big  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.025934
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                          bitty  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.029513
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                       ...  \
Artist        Album                                 Title                      ...
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              ...
              Ariana Grande                         Ariana Grande Tour Guide   ...
                                                    I’m Every Woman/Vogue      ...
                                                    Leave Me Lonely (Reprise)  ...
                                                    Love Me Harder/breathin    ...

term_str                                                                       wondrously  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                     0.0
              Ariana Grande                         Ariana Grande Tour Guide          0.0
                                                    I’m Every Woman/Vogue             0.0
                                                    Leave Me Lonely (Reprise)         0.0
                                                    Love Me Harder/breathin           0.0

term_str                                                                       morе  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You               0.0
              Ariana Grande                         Ariana Grande Tour Guide    0.0
                                                    I’m Every Woman/Vogue       0.0
                                                    Leave Me Lonely (Reprise)   0.0
                                                    Love Me Harder/breathin     0.0

term_str                                                                       pathway  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0.0
              Ariana Grande                         Ariana Grande Tour Guide       0.0
                                                    I’m Every Woman/Vogue          0.0
                                                    Leave Me Lonely (Reprise)      0.0
                                                    Love Me Harder/breathin        0.0

term_str                                                                       starlit  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0.0
              Ariana Grande                         Ariana Grande Tour Guide       0.0
                                                    I’m Every Woman/Vogue          0.0
                                                    Leave Me Lonely (Reprise)      0.0
                                                    Love Me Harder/breathin        0.0

term_str                                                                       travels  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0.0
              Ariana Grande                         Ariana Grande Tour Guide       0.0
                                                    I’m Every Woman/Vogue          0.0
                                                    Leave Me Lonely (Reprise)      0.0
                                                    Love Me Harder/breathin        0.0

term_str                                                                       bluegrass  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0.0
              Ariana Grande                         Ariana Grande Tour Guide         0.0
                                                    I’m Every Woman/Vogue            0.0
                                                    Leave Me Lonely (Reprise)        0.0
                                                    Love Me Harder/breathin          0.0

term_str                                                                       decoration  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                     0.0
              Ariana Grande                         Ariana Grande Tour Guide          0.0
                                                    I’m Every Woman/Vogue             0.0
                                                    Leave Me Lonely (Reprise)         0.0
                                                    Love Me Harder/breathin           0.0

term_str                                                                       jillian  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0.0
              Ariana Grande                         Ariana Grande Tour Guide       0.0
                                                    I’m Every Woman/Vogue          0.0
                                                    Leave Me Lonely (Reprise)      0.0
                                                    Love Me Harder/breathin        0.0

term_str                                                                       newer  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0.0
              Ariana Grande                         Ariana Grande Tour Guide     0.0
                                                    I’m Every Woman/Vogue        0.0
                                                    Leave Me Lonely (Reprise)    0.0
                                                    Love Me Harder/breathin      0.0

term_str                                                                       driftwood
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                    0.0
              Ariana Grande                         Ariana Grande Tour Guide         0.0
                                                    I’m Every Woman/Vogue            0.0
                                                    Leave Me Lonely (Reprise)        0.0
                                                    Love Me Harder/breathin          0.0

[5 rows x 15086 columns]

In [14]:
TFIDF.to_csv('/content/DS5001-Final-Project/TFIDF.csv', sep='|', index=True)

## TFIDF_L2

In [18]:
from numpy.linalg import norm

TFIDF_L2 = TFIDF.apply(lambda x: x / norm(x), 1)

# Keep only words that appear in at least 2 documents
DF = DTM.astype('bool').sum()
TFIDF_L2 = TFIDF_L2.loc[:, DF >= 2]

TFIDF_L2.head()

term_str                                                                              a  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.026760
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.024368
                                                    Leave Me Lonely (Reprise)  0.016547
                                                    Love Me Harder/breathin    0.001524

term_str                                                                            all  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.021714
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.033895
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.005564

term_str                                                                            and  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.009769
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.007624
                                                    Leave Me Lonely (Reprise)  0.002416
                                                    Love Me Harder/breathin    0.017802

term_str                                                                         around  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.023755
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.027812
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                             at  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.015818
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                           away  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.011696
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.013693
                                                    Leave Me Lonely (Reprise)  0.026035
                                                    Love Me Harder/breathin    0.005994

term_str                                                                             be  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.006511
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.007623
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.001669

term_str                                                                         better  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.014109
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.016519
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                            big  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.039164
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                          bitty  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              0.044568
              Ariana Grande                         Ariana Grande Tour Guide   0.000000
                                                    I’m Every Woman/Vogue      0.000000
                                                    Leave Me Lonely (Reprise)  0.000000
                                                    Love Me Harder/breathin    0.000000

term_str                                                                       ...  \
Artist        Album                                 Title                      ...
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You              ...
              Ariana Grande                         Ariana Grande Tour Guide   ...
                                                    I’m Every Woman/Vogue      ...
                                                    Leave Me Lonely (Reprise)  ...
                                                    Love Me Harder/breathin    ...

term_str                                                                       elegies  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                  0.0
              Ariana Grande                         Ariana Grande Tour Guide       0.0
                                                    I’m Every Woman/Vogue          0.0
                                                    Leave Me Lonely (Reprise)      0.0
                                                    Love Me Harder/breathin        0.0

term_str                                                                       eulogize  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   0.0
              Ariana Grande                         Ariana Grande Tour Guide        0.0
                                                    I’m Every Woman/Vogue           0.0
                                                    Leave Me Lonely (Reprise)       0.0
                                                    Love Me Harder/breathin         0.0

term_str                                                                       heartstopping  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                        0.0
              Ariana Grande                         Ariana Grande Tour Guide             0.0
                                                    I’m Every Woman/Vogue                0.0
                                                    Leave Me Lonely (Reprise)            0.0
                                                    Love Me Harder/breathin              0.0

term_str                                                                       insurmountable  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                         0.0
              Ariana Grande                         Ariana Grande Tour Guide              0.0
                                                    I’m Every Woman/Vogue                 0.0
                                                    Leave Me Lonely (Reprise)             0.0
                                                    Love Me Harder/breathin               0.0

term_str                                                                       namedropping  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                       0.0
              Ariana Grande                         Ariana Grande Tour Guide            0.0
                                                    I’m Every Woman/Vogue               0.0
                                                    Leave Me Lonely (Reprise)           0.0
                                                    Love Me Harder/breathin             0.0

term_str                                                                       prose  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0.0
              Ariana Grande                         Ariana Grande Tour Guide     0.0
                                                    I’m Every Woman/Vogue        0.0
                                                    Leave Me Lonely (Reprise)    0.0
                                                    Love Me Harder/breathin      0.0

term_str                                                                       sleaze  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                 0.0
              Ariana Grande                         Ariana Grande Tour Guide      0.0
                                                    I’m Every Woman/Vogue         0.0
                                                    Leave Me Lonely (Reprise)     0.0
                                                    Love Me Harder/breathin       0.0

term_str                                                                       windermere  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                     0.0
              Ariana Grande                         Ariana Grande Tour Guide          0.0
                                                    I’m Every Woman/Vogue             0.0
                                                    Leave Me Lonely (Reprise)         0.0
                                                    Love Me Harder/breathin           0.0

term_str                                                                       wisteria  \
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                   0.0
              Ariana Grande                         Ariana Grande Tour Guide        0.0
                                                    I’m Every Woman/Vogue           0.0
                                                    Leave Me Lonely (Reprise)       0.0
                                                    Love Me Harder/breathin         0.0

term_str                                                                       bеtty
Artist        Album                                 Title
Ariana Grande 13 (Original Broadway Cast Recording) Brand New You                0.0
              Ariana Grande                         Ariana Grande Tour Guide     0.0
                                                    I’m Every Woman/Vogue        0.0
                                                    Leave Me Lonely (Reprise)    0.0
                                                    Love Me Harder/breathin      0.0

[5 rows x 8350 columns]

In [19]:
print("Number of features:", TFIDF_L2.shape[1])

Number of features: 8350

In [20]:
TFIDF_L2.to_csv('/content/DS5001-Final-Project/TFIDF_L2.csv', sep='|', index=True)